# Generated by Django 5.2.5 on 2025-09-03 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('retries', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'url_table',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('page_type', models.CharField(blank=True, max_length=64, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='crawler.urlrecord')),
            ],
            options={
                'db_table': 'page',
            },
        ),
    ]
