# Generated by Django 5.2.5 on 2025-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_urlrecord_remove_page_body_remove_page_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrecord',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
